<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="FluentAssertions" Version="8.2.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.2" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.FileExtensions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.13" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.2" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageVersion Include="Microsoft.VisualStudio.SlowCheetah" Version="4.0.50" />
    <PackageVersion Include="NSubstitute" Version="5.3.0" />
    <PackageVersion Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageVersion Include="MediatR" Version="12.4.1" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.2" />
  </ItemGroup>
</Project>
