<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Repositories\" />
    <Folder Include="Entities\" />
    <Folder Include="Enums\" />
    <Folder Include="Errors\" />
  </ItemGroup>

</Project>
