# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Back-End CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      FOLDER_PATH: Backend
      PROJECT_NAME: wall-et.sln

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      working-directory: ${{ env.FOLDER_PATH }}
      run: dotnet restore ${{ env.PROJECT_NAME }}
    
    - name: Build
      working-directory: ${{ env.FOLDER_PATH }}
      run: dotnet build ${{ env.PROJECT_NAME }} --no-restore
    
    - name: Test
      working-directory: ${{ env.FOLDER_PATH }}
      run: dotnet test --solution ${{ env.PROJECT_NAME }} --no-build --verbosity normal
